### ISSUE TITLE
Email are not indexing

### ISSUE THREAD

**Issue by jfgaudet92** [IMAPMailbox/IMAPmailbox#12]
Hi,
I'm trying to make this work but as for now it only works by CLI and the emails are not indexing. I can see all of them in the CLI.
When I look into splunkd.log, I found a lot of these errors:
**ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py"" __main__.ConfigError

Thanks

**Comment by IMAPMailbox** [comment]
There should be more error message. Otherwise I am not sure. 

---
PJ Balsley

**Comment by jfgaudet92** [comment]
Here's the rest of the logs:
-ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py""     raise ConfigError

ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py""   File "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py", line 153, in initFromOptlist

ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py""     imapProc.initFromOptlist(optlist)

ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py""   File "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py", line 702, in parseArgs

ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py""     parseArgs()

ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py""   File "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py", line 717, in <module>

ERROR ExecProcessor - message from "python "C:\Program Files\Splunk\etc\apps\IMAPmailbox\bin\get_imap_email.py"" Traceback (most recent call last):

**Comment by IMAPMailbox** [comment]
That line error would be if the values for server, user, or password are missing or the config file isn’t being read.  Check system permissions and if the imap.conf file is correct with no odd characters. 

Though I’ve never tested on Windows. Also check splunk base answers 

---
PJ Balsley

**Comment by jfgaudet92** [comment]
I took a look at the post called Windows and apply the changes and also took a look at the local folder in the IMAPmailbox and it looks like the permissions were modified for unknown reason. I fixed it and it's working.
Thanks again.

**Comment by mahmutbilgen** [comment]
we have upgraded splunk search head to 8.1  but then we got those errors. IMAP mailbox app doen't work properly.

```
05-20-2021 08:45:18.210 -0700 ERROR ExecProcessor - message from "/apps/splunk/bin/python3.7 /apps/splunk/etc/apps/IMAPmailbox/bin/get_imap_email.py"   File "/apps/splunk/etc/apps/IMAPmailbox/bin/get_imap_email.py", line 104
05-20-2021 08:45:18.210 -0700 ERROR ExecProcessor - message from "/apps/splunk/bin/python3.7 /apps/splunk/etc/apps/IMAPmailbox/bin/get_imap_email.py"     self.port = 993
05-20-2021 08:45:18.210 -0700 ERROR ExecProcessor - message from "/apps/splunk/bin/python3.7 /apps/splunk/etc/apps/IMAPmailbox/bin/get_imap_email.py"                   ^
05-20-2021 08:45:18.210 -0700 ERROR ExecProcessor - message from "/apps/splunk/bin/python3.7 /apps/splunk/etc/apps/IMAPmailbox/bin/get_imap_email.py" TabError: inconsistent use of tabs and spaces in indentation
```
